[package]
name = "unblock"
version = "0.1.0"
authors = ["Ilya Titkov <ilya@titkov.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
log = "0.4"
env_logger = "0.8"
reqwest = { version = "0.10", features = ["stream", "gzip", "rustls-tls"] }
tokio = {version = "0.2", features = ["macros", "udp", "time", "io-util", "rt-threaded", "sync"]}
serde_json = "1"
serde = {version = "1", features = ["derive"]}
futures-util = "0.3"
bytes = "0.5"
nom = "6"
base64 = "0.13"
priority-queue = "1"
async-trait = "0.1"

[dev-dependencies]
pretty_assertions = "0.6"