[package]
name = "unblock"
version = "0.1.0"
authors = ["Ilya Titkov <ilya@titkov.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
log = "0.4"
env_logger = "0.8"
hex = "0.4"
reqwest = { version = "0.10", features = ["stream", "gzip"] }
tokio = {version = "0.2", features = ["macros", "udp", "time", "io-util", "rt-threaded", "sync"]}
arc-swap = "0.4"
serde_json = "1"
serde = {version = "1", features = ["derive"]}
futures-util = "0.3"
bytes = "0.5"
nom = "5"