version: "3.9"
services:
  unblock:
    build:
      context: .
      network: host
    volumes:
      - ./config.yml:/etc/unblock/config.yml
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - RUST_LOG=info
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    dns: unblock
    depends_on:
      - unblock
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  prometheus:
    image: prom/prometheus:latest
    dns: unblock
    depends_on:
      - unblock
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
